name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Copy JAR
        run: mkdir staging && cp target/*.jar staging

      - name: Package JAR
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
